version: '2'
services:
    ecole-app:
        image: ecole
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ecole-mysql:3306/ecole?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ecole-mysql:
        extends:
            file: mysql.yml
            service: ecole-mysql
